-- liquibase formatted sql
-- changeset fuzis:1
CREATE SCHEMA ACCOUNTS;

-- changeset fuzis:2
CREATE TABLE ACCOUNTS.USERS(
    user_id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    registered_date TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE TABLE ACCOUNTS.TOKEN_TYPES(
    tt_id SERIAL PRIMARY KEY,
    tt_name VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE ACCOUNTS.TOKENS(
    ct_id SERIAL PRIMARY KEY,
    token_key VARCHAR(255) NOT NULL UNIQUE,
    till_date TIMESTAMP WITH TIME ZONE NOT NULL,
    token_type INTEGER NOT NULL,
    token_body TEXT,
    FOREIGN KEY (token_type) REFERENCES ACCOUNTS.TOKEN_TYPES(tt_id) 
);
CREATE TABLE ACCOUNTS.RESET_PASSWORD_REQUESTS(
    rpr_id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    request_date TIMESTAMP NOT NULL DEFAULT NOW(),
    token_id INTEGER NOT NULL UNIQUE,
    FOREIGN KEY (token_id) REFERENCES ACCOUNTS.TOKENS(ct_id), 
    FOREIGN KEY (user_id) REFERENCES ACCOUNTS.USERS(user_id) 
);

-- changeset fuzis:3
CREATE SCHEMA SSO;