-- rollback fuzis:3
DROP SCHEMA SSO CASCADE;

-- rollback fuzis:2
DROP TABLE ACCOUNTS.RESET_PASSWORD_REQUESTS;
DROP TABLE ACCOUNTS.TOKENS;
DROP TABLE ACCOUNTS.TOKEN_TYPES;
DROP TABLE ACCOUNTS.USERS;

-- rollback fuzis:1
DROP SCHEMA ACCOUNTS;
