package com.fuzis.integrationbus.route;

import com.fuzis.integrationbus.exception.AuthenticationException;
import com.fuzis.integrationbus.exception.NoRequiredHeader;
import com.fuzis.integrationbus.exception.ServiceFall;
import org.apache.camel.Exchange;
import org.apache.camel.LoggingLevel;
import org.apache.camel.builder.RouteBuilder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class AccountUserAdminRoutes extends RouteBuilder {

    public AccountUserAdminRoutes() {

    }

    @Override
    public void configure() throws Exception {
        errorHandler(defaultErrorHandler()
                .maximumRedeliveries(0)
                .retryAttemptedLogLevel(LoggingLevel.WARN));

        from("platform-http:/oapi/v1/accounts/admin/description?httpMethodRestrict=PUT")
                .routeId("accounts-user-put-description-admin-route")
                .onException(NoRequiredHeader.class)
                    .handled(true)
                    .to("direct:bad-request-error-handler")
                .end()
                .onException(AuthenticationException.class)
                    .handled(true)
                    .to("direct:auth-error-handler")
                .end()
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("New-Description, X-User-Change-ID"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("profile-watch,profile-change,manage-accounts"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("PUT"))
                .setHeader("X-Service", constant("Accounts"))
                .setHeader("X-Service-Request", simple("api/v1/accounts/user/${header.X-User-Change-ID}/description"))
                .setHeader(Exchange.CONTENT_TYPE, constant("application/x-www-form-urlencoded"))
                .setBody(simple("description=${header.New-Description}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/accounts/admin/birth-date?httpMethodRestrict=PUT")
                .routeId("accounts-user-put-birth-date-admin-route")
                .onException(NoRequiredHeader.class)
                    .handled(true)
                    .to("direct:bad-request-error-handler")
                .end()
                .onException(AuthenticationException.class)
                    .handled(true)
                    .to("direct:auth-error-handler")
                .end()
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("New-Birth-Date,X-User-Change-ID"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("profile-watch,profile-change,manage-accounts"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("PUT"))
                .setHeader("X-Service", constant("Accounts"))
                .setHeader("X-Service-Request", simple("api/v1/accounts/user/${header.X-User-Change-ID}/birth-date"))
                .setHeader(Exchange.CONTENT_TYPE, constant("application/x-www-form-urlencoded"))
                .setBody(simple("birth_date=${header.New-Birth-Date}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/accounts/admin/nickname?httpMethodRestrict=PUT")
                .routeId("accounts-user-put-nickname-admin-route")
                .onException(NoRequiredHeader.class)
                    .handled(true)
                    .to("direct:bad-request-error-handler")
                .end()
                .onException(AuthenticationException.class)
                    .handled(true)
                    .to("direct:auth-error-handler")
                .end()
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("New-Nickname,X-User-Change-ID"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("profile-watch,profile-change,manage-accounts"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("PUT"))
                .setHeader("X-Service", constant("Accounts"))
                .setHeader("X-Service-Request", simple("api/v1/accounts/user/${header.X-User-Change-ID}/nickname"))
                .setHeader(Exchange.CONTENT_TYPE, constant("application/x-www-form-urlencoded"))
                .setBody(simple("nickname=${header.New-Nickname}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/accounts/admin/email?httpMethodRestrict=PUT")
                .routeId("accounts-user-put-email-admin-route")
                .onException(NoRequiredHeader.class)
                    .handled(true)
                    .to("direct:bad-request-error-handler")
                .end()
                .onException(AuthenticationException.class)
                    .handled(true)
                    .to("direct:auth-error-handler")
                .end()
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("New-Email,X-User-Change-ID"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("profile-watch,profile-change,manage-accounts"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("PUT"))
                .setHeader("X-Service", constant("Accounts"))
                .setHeader("X-Service-Request", simple("api/v1/accounts/user/${header.X-User-Change-ID}/email"))
                .setHeader(Exchange.CONTENT_TYPE, constant("application/x-www-form-urlencoded"))
                .setBody(simple("email=${header.New-Email}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/accounts/admin/password?httpMethodRestrict=PUT")
                .routeId("accounts-user-put-password-admin-route")
                .onException(NoRequiredHeader.class)
                    .handled(true)
                    .to("direct:bad-request-error-handler")
                .end()
                .onException(AuthenticationException.class)
                    .handled(true)
                    .to("direct:auth-error-handler")
                .end()
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("New-Password,X-User-Change-ID"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("profile-watch,profile-change,manage-accounts"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("PUT"))
                .setHeader("X-Service", constant("Accounts"))
                .setHeader("X-Service-Request", simple("api/v1/accounts/user/${header.X-User-Change-ID}/password"))
                .setHeader(Exchange.CONTENT_TYPE, constant("application/x-www-form-urlencoded"))
                .setBody(simple("password=${header.New-Password}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/accounts/admin/username?httpMethodRestrict=PUT")
                .routeId("accounts-user-put-username-admin-route")
                .onException(NoRequiredHeader.class)
                    .handled(true)
                    .to("direct:bad-request-error-handler")
                .end()
                .onException(AuthenticationException.class)
                    .handled(true)
                    .to("direct:auth-error-handler")
                .end()
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("New-Username,X-User-Change-ID"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("profile-watch,profile-change,manage-accounts"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("PUT"))
                .setHeader("X-Service", constant("Accounts"))
                .setHeader("X-Service-Request", simple("api/v1/accounts/user/${header.X-User-Change-ID}/username"))
                .setHeader(Exchange.CONTENT_TYPE, constant("application/x-www-form-urlencoded"))
                .setBody(simple("username=${header.New-Username}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/accounts/admin/ban?httpMethodRestrict=POST")
                .routeId("accounts-user-ban-route")
                .onException(NoRequiredHeader.class)
                    .handled(true)
                    .to("direct:bad-request-error-handler")
                .end()
                .onException(AuthenticationException.class)
                    .handled(true)
                    .to("direct:auth-error-handler")
                .end()
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("X-User-Change-ID"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("profile-watch,profile-change,manage-accounts"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("POST"))
                .setHeader("X-Service", constant("Accounts"))
                .setHeader("X-Service-Request", simple("api/v1/accounts/user/${header.X-User-Change-ID}/ban"))
                .setBody(constant(""))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/accounts/admin/unban?httpMethodRestrict=POST")
                .routeId("accounts-user-unban-route")
                .onException(NoRequiredHeader.class)
                    .handled(true)
                    .to("direct:bad-request-error-handler")
                .end()
                .onException(AuthenticationException.class)
                    .handled(true)
                    .to("direct:auth-error-handler")
                .end()
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("X-User-Change-ID"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant("profile-watch,profile-change,manage-accounts"))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("POST"))
                .setHeader("X-Service", constant("Accounts"))
                .setHeader("X-Service-Request", simple("api/v1/accounts/user/${header.X-User-Change-ID}/unban"))
                .setBody(constant(""))
                .to("direct:sd-call-finalize");
    }
}
