package com.fuzis.integrationbus.route;

import com.fuzis.integrationbus.exception.AuthenticationException;
import com.fuzis.integrationbus.exception.ServiceFall;
import org.apache.camel.Exchange;
import org.apache.camel.LoggingLevel;
import org.apache.camel.builder.RouteBuilder;
import org.springframework.stereotype.Component;

@Component
public class BooksCommonRoutes extends RouteBuilder {
    @Override
    public void configure() {
        errorHandler(defaultErrorHandler()
                .maximumRedeliveries(0)
                .retryAttemptedLogLevel(LoggingLevel.WARN));

        from("platform-http:/oapi/v1/popular/collections?httpMethodRestrict=GET")
                .routeId("books-popular-collections-route")
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/popular/collections"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/popular/users?httpMethodRestrict=GET")
                .routeId("books-popular-users-route")
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/popular/users"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/popular/books?httpMethodRestrict=GET")
                .routeId("books-popular-books-route")
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/popular/books"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/user?httpMethodRestrict=GET")
                .routeId("user-books-route")
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("userId"))
                .to("direct:check-params")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/users/${header.userId}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/user/subscribers?httpMethodRestrict=GET")
                .routeId("user-books-subscribers-route")
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("userId"))
                .to("direct:check-params")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/users/${header.userId}/subscribers"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/user/subscriptions?httpMethodRestrict=GET")
                .routeId("user-books-subscriptions-route")
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("userId"))
                .to("direct:check-params")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/users/${header.userId}/subscriptions"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/user/collections?httpMethodRestrict=GET")
                .routeId("user-books-collections-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("userId"))
                .to("direct:check-params")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/users/${header.userId}/collections"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/collections?httpMethodRestrict=GET")
                .routeId("user-books-collection-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("collectionId"))
                .to("direct:check-params")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/collections/${header.collectionId}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/collections/books?httpMethodRestrict=GET")
                .routeId("user-books-collections-books-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("collectionId"))
                .to("direct:check-params")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/collections/${header.collectionId}/books"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/collections/books/auth?httpMethodRestrict=GET")
                .routeId("user-books-collections-books-auth-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("collectionId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant(""))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("userId", simple("${header.X-User-ID}"))
                .setHeader("X-Service-Request", simple("api/v1/collections/${header.collectionId}/books"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/collection/auth?httpMethodRestrict=GET")
                .routeId("user-books-collection-auth-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("collectionId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant(""))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("userId", simple("${header.X-User-ID}"))
                .setHeader("X-Service-Request", simple("api/v1/collections/${header.collectionId}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/books?httpMethodRestrict=GET")
                .routeId("user-books-books-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("bookId"))
                .to("direct:check-params")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/books/${header.bookId}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/books/reviews?httpMethodRestrict=GET")
                .routeId("user-books-reviews-books-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("bookId"))
                .to("direct:check-params")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("X-Service-Request", simple("api/v1/books/${header.bookId}/reviews"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/subscribe?httpMethodRestrict=POST")
                .routeId("user-books-subscribe-route")
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                    .handled(true)
                    .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("userOnId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant(""))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("POST"))
                .setHeader("X-Service", constant("Books"))
                .setHeader(Exchange.CONTENT_TYPE, constant("application/x-www-form-urlencoded"))
                .setBody(simple("userId=${header.X-User-ID}&userOnId=${header.userOnId}"))
                .setHeader("X-Service-Request", simple("api/v1/subscribers/subscribe"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/unsubscribe?httpMethodRestrict=POST")
                .routeId("user-books-unsubscribe-route")
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                    .handled(true)
                    .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("userOnId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant(""))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("POST"))
                .setHeader("X-Service", constant("Books"))
                .setHeader(Exchange.CONTENT_TYPE, constant("application/x-www-form-urlencoded"))
                .setBody(simple("userId=${header.X-User-ID}&userOnId=${header.userOnId}"))
                .setHeader("X-Service-Request", simple("api/v1/subscribers/unsubscribe"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/is-subscriber?httpMethodRestrict=GET")
                .routeId("user-books-is-subscriber-route")
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                    .handled(true)
                    .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("userOnId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant(""))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("userId", simple("${header.X-User-ID}"))
                .setBody(constant(""))
                .setHeader("X-Service-Request", simple("api/v1/subscribers/is-subscriber"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/library-collections?httpMethodRestrict=GET")
                .routeId("user-books-library-collections-route")
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                    .handled(true)
                    .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Roles-Required", constant(""))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("userId", simple("${header.X-User-ID}"))
                .setBody(constant(""))
                .setHeader("X-Service-Request", simple("api/v1/library/visible-collections"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/library-books?httpMethodRestrict=GET")
                .routeId("user-books-library-books-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Roles-Required", constant(""))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("userId", simple("${header.X-User-ID}"))
                .setBody(constant(""))
                .setHeader("X-Service-Request", simple("api/v1/library/visible-books"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/library-wishlist?httpMethodRestrict=GET")
                .routeId("user-books-library-wishlist-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Roles-Required", constant(""))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("userId", simple("${header.X-User-ID}"))
                .setBody(constant(""))
                .setHeader("X-Service-Request", simple("api/v1/library/wishlist-books"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/book?httpMethodRestrict=PUT")
                .routeId("user-books-book-put-route")
                .onException(ServiceFall.class)
                    .handled(true)
                    .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                    .handled(true)
                    .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("bookId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant(""))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("PUT"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("userId", simple("${header.X-User-ID}"))
                .setHeader("X-Service-Request", simple("api/v1/books/${header.bookId}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/book?httpMethodRestrict=POST")
                .routeId("user-books-book-post-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Roles-Required", constant(""))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("POST"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("userId", simple("${header.X-User-ID}"))
                .setHeader("X-Service-Request", simple("api/v1/books"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/book?httpMethodRestrict=DELETE")
                .routeId("user-books-book-delete-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("bookId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant(""))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("DELETE"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("userId", simple("${header.X-User-ID}"))
                .setHeader("X-Service-Request", simple("api/v1/books/${header.bookId}"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/book/reviews/my?httpMethodRestrict=GET")
                .routeId("user-books-book-my-review-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("bookId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant(""))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("userId", simple("${header.X-User-ID}"))
                .setHeader("X-Service-Request", simple("api/v1/books/${header.bookId}/reviews/my"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/book/reviews?httpMethodRestrict=POST")
                .routeId("user-books-book-post-review-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("bookId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant(""))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("POST"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("userId", simple("${header.X-User-ID}"))
                .setHeader("X-Service-Request", simple("api/v1/books/${header.bookId}/reviews"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/book/reviews?httpMethodRestrict=PUT")
                .routeId("user-books-book-put-review-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("bookId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant(""))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("PUT"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("userId", simple("${header.X-User-ID}"))
                .setHeader("X-Service-Request", simple("api/v1/books/${header.bookId}/reviews"))
                .to("direct:sd-call-finalize");

        from("platform-http:/oapi/v1/book/reviews?httpMethodRestrict=DELETE")
                .routeId("user-books-book-delete-review-route")
                .onException(ServiceFall.class)
                .handled(true)
                .to("direct:service-error-handler")
                .end()
                .onException(AuthenticationException.class)
                .handled(true)
                .to("direct:auth-error-handler")
                .end()
                .setHeader("X-Headers-Required", constant("bookId"))
                .to("direct:check-params")
                .setHeader("X-Roles-Required", constant(""))
                .to("direct:auth")
                .setHeader(Exchange.HTTP_METHOD, constant("DELETE"))
                .setHeader("X-Service", constant("Books"))
                .setHeader("userId", simple("${header.X-User-ID}"))
                .setHeader("X-Service-Request", simple("api/v1/books/${header.bookId}/reviews"))
                .to("direct:sd-call-finalize");
    }
}

